# Generated by Django 4.1.7 on 2023-08-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='equalmedicine',
            name='medicine1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='med1', to='core.medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equalmedicine',
            name='medicine2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='med2', to='core.medicine'),
            preserve_default=False,
        ),
    ]
